### ISSUE TITLE
Fortls not working

### ISSUE THREAD

**Issue by mdeberts** [gnikit/fortls#57]
Hello,

I installed fortls on RockyLinux using pip3 install fortls --user
That worked

I need fortls for VsCode but I get an error
'''Error starting fortls: Check that fortls is in your PATH or that "fortran.fortls.path" is pointing to a fortls binary.'''

I changed it from standard setting, to "fortls" to my actual binary in "/home/mdeberts/.local/bin/fortls" but the error remains, in UI and in settings.json - nothing worked.

Also if I type in terminal "fortls" I get the following error:

[mdeberts@oflks103 ~]$ fortls
Traceback (most recent call last):
  File "/home/mdeberts/.local/bin/fortls", line 7, in <module>
    from fortls.__init__ import main
  File "/home/mdeberts/.local/lib/python3.6/site-packages/fortls/__init__.py", line 10, in <module>
    from .helper_functions import resolve_globs, only_dirs
  File "/home/mdeberts/.local/lib/python3.6/site-packages/fortls/helper_functions.py", line 1
    from __future__ import annotations

**Comment by gnikit** [comment]
Yes, you are correct. We do not support python 3.6. I don't remember why specifically I made that decision 2 months ago, but it had to do with missing some features for typed Python. You can always download miniconda and install `fortls` through it, the installation size should be very small

**Comment by gnikit** [comment]
@mdeberts did you resolve your problem?

**Comment by mdeberts** [comment]
> @mdeberts did you resolve your problem?

Since I work in a company within a larger project it's not easily done to upgrade the python version.
Hence I am using fortran-language-server instead so I can circumvent the dependency problems, since it's working with python 3.6.8.
But thanks for your help.

**Comment by gnikit** [comment]
I will see if I can back-port python 3.6 now that the project files have been updated. I don't think it should be that hard. Obviously pip will pull a bunch of project dependencies, as opposed to now which we have none.

**Comment by mdeberts** [comment]
> I will see if I can back-port python 3.6 now that the project files have been updated. I don't think it should be that hard. Obviously pip will pull a bunch of project dependencies, as opposed to now which we have none.

OK that would be great, thanks for your time.

**Comment by gnikit** [comment]
So I had a look and I am afraid there is no straightforward way to support Python 3.6. 

It is not that the functionality of the server contains crucial features that Python 3.6 is unable to implement, but rather that I have switched, to using types i.e. `annotations` which are not supported in Python 3.6. So the only way to get the server to work would be to go and remove all typing signatures or replace them with their deprecated versions.

That is because, the `__future__` module is imported at compile time so we cannot do any try-except tricks to account for older versions of Python. I hope that clarifies things a bit.

On a more serious note [Python 3.6 reached EOL](https://endoflife.date/python) in December of last year so projects (like `fortls`) have started dropping support in order to facilitate for the newer Python features. For example Python types with `mypy` is a major help since they effectively can spot runtime errors.

## Solution

The solution I suggested does not actually require you to change your project's Python version or the default Python version, you merely have to create a virtual environment of Python >= 3.7 just for `forlts`

The steps should look something like this:

## miniconda

1. Download [miniconda](https://docs.conda.io/en/latest/miniconda.html)
2. Run the installer on the user level, no sudo needed. Make sure towards the end of the install you choose for conda to **not auto-activate** by default. 
3. Run `conda activate base`

## venv

1. download a python3 version >= 3.7 from python webpage or your package manager e.g. `sudo apt install python3.9-dev` see [here](https://askubuntu.com/questions/339/how-can-i-install-a-package-without-root-access) for non-root installs of apt
2. Create a venv `/path/to/new/python3.7 -m venv ./some/path/fortlsvenv`
3. Activate `source ./some/path/fortlsvenv/bin/activate` for Unix or `some\path\fortlsvenv\bin\activate.bat` for Windows to activate you venv

------
4. `pip install fortls`
5. `pip show fortls` to get the install location, use this full path to launch fortls in VSCode, or emacs, etc.

**Comment by mdeberts** [comment]
> 
Sorry for the delayed reply.
Thanks, that kinda did the trick.
As I am using VsCode on a remote server via remote-ssh plugin. Hence, I can not activate the python 3.9 environment and then start VsCode within this environment.
So if I tell Modern Fortran in VsCode the path from "pip show fortls" it did not work.
But I changed that to 

.../envs/py39/bin/fortls

with py39 the name of the miniconda environment
and now it works, except for 

Peek/Go to definitions and references

which are still not found.

But I am not sure if that is a language server issue or a problem with my complicated setup. So the definitions are not found, but hover over the function will draw a popup.

**Comment by gnikit** [comment]
I am glad that you got it somewhat working. I have a similar setup on a remote workstation with SSH and miniconda which is still running Ubuntu 18.04

As for the rest, in the order mentionned:

> That's the output I get if I want to go to the definition of "mod(5, 2)"

I don't think you can GoTo definitions of intrinsics

> It also doesn't find fortran libraries / modules I installed in a folder outside my VsCode Workspace.

fortls for the time being works only for files inside your workspace. I have to tweak some things to get it working for individual files

>[Error - 2:00:29 PM] Request textDocument/implementation failed
> ...
> AttributeError: 'NoneType' object has no attribute 'get_type'

That seems like a bug. Could you please do the following on a separate GitHub issue:

1. Post a Minimal Working Example were I can replicate the bug
2. Post your fortls settings both from VS Code (if any) and from the `.fortls` configuration file (if present)

**Comment by mdeberts** [comment]
> I am glad that you got it somewhat working. I have a similar setup on a remote workstation with SSH and miniconda which is still running Ubuntu 18.04
> 
> As for the rest, in the order mentioned:
> 
> > That's the output I get if I want to go to the definition of "mod(5, 2)"
> 
> I don't think you can GoTo definitions of intrinsics
> 
> > It also doesn't find fortran libraries / modules I installed in a folder outside my VsCode Workspace.
> 
> fortls for the time being works only for files inside your workspace. I have to tweak some things to get it working for individual files
> 
> > [Error - 2:00:29 PM] Request textDocument/implementation failed
> > ...
> > AttributeError: 'NoneType' object has no attribute 'get_type'
> 
> That seems like a bug. Could you please do the following on a separate GitHub issue:
> 
>     1. Post a Minimal Working Example were I can replicate the bug
> 
>     2. Post your fortls settings both from VS Code (if any) and from the `.fortls` configuration file (if present)

Ok made a new report.
Can you tell me if there is a workaround for the language server not finding modules in a folder outside the VsCode Workspace?

I added the folder with the corresponding modules to my VsCode Workspace, but it didn't help.

**Comment by mdeberts** [comment]
I tried adding the folder to the repository of my external lib I am using (fox xml parser) to my workspace.
But still the language server didn't find the necessary files, so I could jump to a module I use by ctrl+left-clicking.

What did work is copying the whole repository inside the folder of my main.f95
Then I was able to hop through the functions and also the autocompletion would tell me subroutines from the fox repository.

But that's a rough workaround, can't do that for every external fortran modules I am using =)

Do you have an idea for a better workaround?
I'm by no means an expert and rather novice, so I have not the very best overview of what would be a good solution.
Thanks for the time and effort you put into this project!

**Comment by gnikit** [comment]
I know it is annoying, but before I add any new major features, like out of root support, I first need to refactor the code to more manageable and modular functions. 

The only other workaround I can think of is to use symlinks inside your workspace folder, that should hopefully work

**Comment by gnikit** [comment]
As you mentioned, you can add in your `.fortls` configuration file source directories e.g. `"source_dirs": ["/my/ext/dir1/**"]`. This might be what you are asking for. FYI the GoTo implementation is not currently tested, so I actually can't recall of the top of my head if you can Jump to source files outside of your root if they are specified in your `source_dirs`.

In the near future I will get around making the gotos more robust but until then feel free to use them, as they should work, but report here any bugs that you encounter.
